CREATE DATABASE IF NOT EXISTS ACTUARIAL_AI_DEV;
CREATE SCHEMA IF NOT EXISTS ACTUARIAL_AI_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS ACTUARIAL_AI_DEV.CURATED;
CREATE SCHEMA IF NOT EXISTS ACTUARIAL_AI_DEV.RUNS;
CREATE SCHEMA IF NOT EXISTS ACTUARIAL_AI_DEV.APP;

CREATE TABLE IF NOT EXISTS ACTUARIAL_AI_DEV.RAW.FILE_MANIFEST (
  RUN_ID STRING,
  FILE_ID STRING,
  RELATIVE_PATH STRING,
  FILE_NAME STRING,
  ROLE STRING,
  SHA256 STRING,
  SIZE_BYTES NUMBER,
  MODIFIED_AT_UTC STRING,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACTUARIAL_AI_DEV.RAW.VALUATION_RESULTS (
  RUN_ID STRING,
  VALUATION_PERIOD STRING,
  PRODUCT STRING,
  PORTFOLIO STRING,
  COHORT STRING,
  MEASURE STRING,
  AMOUNT NUMBER(38, 10),
  CURRENCY STRING,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACTUARIAL_AI_DEV.RAW.VALUATION_BRIDGE (
  RUN_ID STRING,
  FROM_PERIOD STRING,
  TO_PERIOD STRING,
  PRODUCT STRING,
  PORTFOLIO STRING,
  MEASURE STRING,
  DRIVER STRING,
  AMOUNT NUMBER(38, 10),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACTUARIAL_AI_DEV.CURATED.MOVEMENT_RESULTS (
  RUN_ID STRING,
  FROM_PERIOD STRING,
  TO_PERIOD STRING,
  PRODUCT STRING,
  PORTFOLIO STRING,
  MEASURE STRING,
  DRIVER STRING,
  AMOUNT NUMBER(38, 10),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACTUARIAL_AI_DEV.RUNS.VALIDATION_RESULTS (
  RUN_ID STRING,
  CHECK_NAME STRING,
  STATUS STRING,
  SEVERITY STRING,
  MESSAGE STRING,
  DETAILS STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACTUARIAL_AI_DEV.RUNS.RUN_LOG (
  RUN_ID STRING,
  STEP STRING,
  STATUS STRING,
  MESSAGE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACTUARIAL_AI_DEV.APP.DASHBOARD_SUMMARY (
  RUN_ID STRING,
  FROM_PERIOD STRING,
  TO_PERIOD STRING,
  PRODUCT STRING,
  PORTFOLIO STRING,
  MEASURE STRING,
  DRIVER STRING,
  AMOUNT NUMBER(38, 10),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

